services:
  backend:
    container_name: backendWPT
    build:
        context: ./server
        dockerfile: Containerfile.prod
    env_file:
      - ./.env.prod
    depends_on:
      - db
    



  frontend:
    container_name: frontendWPT
    build:
        context: ./user
        dockerfile: Containerfile.prod
    ports:
      - ":80"
    

  db:
    image: postgres:16
    
    env_file:
      - ./.env.prod
    volumes:
        - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/routes.yml:/etc/traefik/routes.yml:ro
      - ./letsencrypt:/letsencrypt
    
volumes:
    postgres_data_prod:

