services:
  backend:
    container_name: backendWPT
    build:
        context: ./server/
        dockerfile: Containerfile.dev
    env_file:
      - ./.env.dev
    volumes:
        - ./server:/app
        - ./server/uploads:/uploads
    ports:
      - "8080:8080"
    depends_on:
      - db


  frontend:
    container_name: frontendWPT
    build:
        context: ./user/
        dockerfile: Containerfile.dev
    volumes:
        - ./user/webpartytime:/app/webpartytime
    ports:
        - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:16
    volumes:
        - postgres_data:/var/lib/postgresql/data
    
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

volumes:
    postgres_data:
